github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: alopatindev
open_collective: alopatindev
ko_fi: alopatindev
tidelift:
community_bridge:
liberapay: alopatindev
issuehunt:
otechie:
lfx_crowdfunding:
custom: ['https://github.com/codonaft/broadcastr#support', 'https://codonaft.com/sponsor']
